frase = str(input('Digite uma frase:')).upper().strip()
print('A letra A aparece {} vezes na frase.'.format(frase.count('A')))
espaco = frase.replace(' ', '')
print('A primeira letra A apareceu na posição {}'.format(espaco.find('A')+1))
print('A última letra A apareceu na posição {}'.format(espaco.rfind('A')+1))